### ISSUE TITLE
Data Studio graphing 0 when there is no data point

### ISSUE THREAD

**Issue by markroth8** [dsjoerg/ca_visit_tracking#50]
Example: CA / Kings County on 2020-03-23 for Age 65+, Grocery is 0 because it is missing in the file.

Reported by @dsjoerg

**Comment by dsjoerg** [comment]
We are currently hiding GDS because:
* Kara is no longer our primary user for CA: it's Joe and Noah on our team. And they seem to be fine with the regular site rather than GDS.
* we have been changing ergonomics on the site a bit and GDS hasn't kept up
* we dont currently have a process for updating GDS.

So, closing.
